### ISSUE TITLE
Open notifications in new tab

### ISSUE THREAD

**Issue by ajkblue** [sindresorhus/notifier-for-github-safari#4]
Instead of opening GitHub notifications over the current window that I am in, it would be better to open up the notifications page in a new tab. Or it could be a option in the Extension to choose whether to open up in a new tab or over the current window.

**Comment by sindresorhus** [comment]
Agreed. Should be the default. No option needed. PR welcome :)

**Comment by irliao** [comment]
@ajkblue Do you mean opening the page in a new tab at the background (will not activate automatically) instead of the foreground (activates right away)?
@sindresorhus I can try my best to implement it

**Comment by ajkblue** [comment]
@irliao I believe it would be best to activate in the foreground, since I am directly clicking the button to show my notifications.

**Comment by irliao** [comment]
@ajkblue Doesn't the current latest version of this extension already do that?

**Comment by ajkblue** [comment]
@irliao The current version opens the GitHub notification page in whatever tab is currently open. I am proposing that the notifications should open in a new, foreground tab and **not** overwrite the tab that's already open.

**Comment by irliao** [comment]
@ajkblue Thank you for clarifying, I was able to reproduce the behavior you described. When I open and load a new tab (say www.google.com for example) and immediately press the extension toolbar button, it does override the currently active tab. The weird thing is on some tabs it does not override it and opens it in a new foreground tab. I will investigate this when I get a chance.
