### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github-safari#6]
I haven't used this extension for years and it could use an active maintainer that actually cares and can review PRs, triage issues, etc.

**Comment by Haroenv** [comment]
What about the developer license needed now, I suppose the hypothetical maintainer should provide that one himself?

**Comment by sindresorhus** [comment]
It can continue to use mine.

**Comment by Haroenv** [comment]
I think I would be up for it, I always look at notifications pretty fast, so I can stay updated.

**Comment by sindresorhus** [comment]
Awesome. You're now a collaborator :)

The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Follow the existing [code style](https://github.com/sindresorhus/xo) (Tip: `$ xo --fix` can fix many issues) and ensure `npm test` passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to [squash](http://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request) their commits or do it for them manually.

**Comment by sindresorhus** [comment]
Feel free to open issues for new features you'd like to see. See the [Chrome extension](https://github.com/sindresorhus/notifier-for-github-chrome) for inspiration.

**Comment by Haroenv** [comment]
Do you mean squashing after the merge or before it's merged?

**Comment by SamVerschueren** [comment]
If you ask the contributor, it's before merge, if you do it yourself, there are 2 options.
1. You use the `Merge Pull Request` button from GitHub and then squash them afterwards
2. You checkout the PR, squash and then merge with master

**Comment by SamVerschueren** [comment]
Either what you use, just make sure in the end, the history is clean ;).

**Comment by sindresorhus** [comment]
2. Is preferably as you wouldn't have to force push to master.

**Comment by Haroenv** [comment]
Okay, that's what I assumed!

**Comment by sindresorhus** [comment]
If you're uncomfortable with this, just ask the contributor to squash, or I can manually merge it for you. Doesn't matter :)

**Comment by amio** [comment]
Just one day after sindresorhus's last reply, Github give us this: https://github.com/blog/2141-squash-your-commits 😂

**Comment by sindresorhus** [comment]
Apple has deprecated JS-based Safari extensions, so I'm deprecating this project.
